In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import cross_val_score
import seaborn as sns
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.gaussian_process import GaussianProcessClassifier
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import mean_squared_error
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from math import sqrt
from sklearn.metrics import f1_score
from sklearn.metrics import recall_score

In [4]:
df = pd.read_csv("T1_Product.csv")
df['productLetterGrade'].replace(to_replace=["A","F"], value=["1","2"],inplace=True)

In [5]:
df

,year,semester,timeInterval,teamNumber,semesterId,teamMemberCount,femaleTeamMembersPercent,teamLeadGender,teamDistribution,teamMemberResponseCount,...,standardDeviationUniqueCommitMessagePercentByStudent,averageCommitMessageLengthTotalByStudent,standardDeviationCommitMessageLengthTotalByStudent,averageCommitMessageLengthAverageByStudent,standardDeviationCommitMessageLengthAverageByStudent,averageCommitMessageLengthStandardDeviationByStudent,issueCount,onTimeIssueCount,lateIssueCount,productLetterGrade
0,2012.0,Fall,1.0,134.0,1.0,3.0,0.0000,M,Global,1.0,...,0.0,57.0,0.0,14.25,0.0,14.463316,2,2,0,1
1,2013.0,Fall,1.0,167.0,3.0,3.0,0.3333,F,Global,3.0,...,0.0,127.0,0.0,31.75,0.0,6.533567,2,2,0,2
2,2013.0,Fall,1.0,170.0,3.0,4.0,0.0000,M,Global,3.0,...,0.0,0.0,0.0,0.00,0.0,0.000000,1,1,0,2
3,2012.0,Fall,1.0,127.0,1.0,6.0,0.0000,M,Local,1.0,...,0.0,45.0,0.0,22.50,0.0,4.500000,0,0,0,1
4,2012.0,Fall,1.0,130.0,1.0,6.0,0.1667,M,Local,3.0,...,0.0,13.0,0.0,13.00,0.0,0.000000,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.00,0.0,0.000000,0,0,0,1
70,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.00,0.0,0.000000,0,0,0,1
71,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.00,0.0,0.000000,0,0,0,1
72,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.00,0.0,0.000000,0,0,0,2
73,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.00,0.0,0.000000,0,0,0,1